services:
  lab:
    container_name: jupyter
    build: ./app/jupyter
    volumes:
      - ./app/jupyter/resources:/app
    environment:
      - PASSWORD=jupy
      - JUPYTER_TOKEN=jupy
    ports:
      - 8888:8888